weights = {'A': 71.03711,
           'C': 103.00919,
           'D': 115.02694,
           'E': 129.04259,
           'F': 147.06841,
           'G': 57.02146,
           'H': 137.05891,
           'I': 113.08406,
           'K': 128.09496,
           'L': 113.08406,
           'M': 131.04049,
           'N': 114.04293,
           'P': 97.05276,
           'Q': 128.05858,
           'R': 156.10111,
           'S': 87.03203,
           'T': 101.04768,
           'V': 99.06841,
           'W': 186.07931,
           'Y': 163.06333}


def calc_pro_weight(prot_seq):
    weight = 0
    for aa in prot_seq:
        weight += weights[aa]
    return weight

def main():
    #prot_seq = "RPMDITDHMLDSWLISAQWEMLRTGMVEFGPTEWISIWYTIGIRKKLWRPHIGHSMAFYDDETKMCPCNDWTQCGQDKRWYRVRKAYRYVRDCWYGDAHHKGMVEEMQMRRHKPLLNGMMAQYDQMETYFEKMTGSMWSIEASCGQNQIPLIQWTDCKDISRQVNNDQDYMMQPAMLQKCVHRWLTGWFAVCQFYHCVIFEYYTEFNNISQTWVPCSMEQNRDEDNDHPRHLNMRLMHWKKIWNQVAGLRFGDFTNYRIVNGMWSGEVHTGAKKKANTVVNEAAVNDRKSYNPEKRGLLGQPVQSGGHWLAQLAITLVEIGFYRPYFNENGKCYIHKPNGYRLNINKQYITSKKEYSFVCMRYEIGRAWEEDPESTIMDIFMPHELQVHEVARSQFDQDYLSFVFGLICVEGHFIFVAWTHQSALYKFWKTSFAELRCKPYDCYSKEFYIKPTHDPSMLIGMLCGFSWEPWHSVHHGLHSVAGIRAHEMVWRAERHVFGCPWHQIFVSWFGSGGKHKIQIQVHIVQRVWGMHVYHTDGCNILFYIVYECFARNNVEWAIGKRFCSAGYNTCMYSMWFCRRRCNMLYIDSIGVKITTQKPELLAPIIAYGEIGKDVDGLLYMWQITCLWQNRHHMATSVPYVKSMHRGQHTMCSEELDVSWERNQCMLKAQGPTCDANSCQCAYKSWILSKVECVHYLVHKNFWDPIDRLDSANLRGSYGIEPYWCDLDGINEVMFYMEVVGAWDVGCRVHCVSRHLTLQPDVQPDCAFRIGVVVKTHRVHIHVWFMQSQPVMIMTPWSQAHNSTDLWYIIFFHVMVQGQCFSGGKEVTIWWPHWLYDTGNENWREDFTIPNMIIRQLTWGNRFQENQMSNMCEYHTLLMVHKNMQRNYENWSAAKNRCYFETHGEYDYQWCMHVI"
    prot_seq = input("Enter the amino acid sequence to calculate weight for: \n")
    pro_weight = calc_pro_weight(prot_seq)
    pro_weight = '%0.3f' % pro_weight
    print(f"Weight of the amino acid sequence is: {pro_weight}")
    # Insert code to convert into da, Kda and all metrics

if __name__ == "__main__":
    main()