"""

To find motifs in DNA sequence.

"""


def main():
    # input_seq = "TGTGCAACTTGAAATTTGAAATTTGAAATAAATTGAAATCATGTTGAAATTTGAAATCTATTTGAAATTTATGTATTGAAATTTGAAATATCGTTGAAATTGCTTGAAATTTGAAATCGTTGAAATCCGATTGAAATTGATACCATGTGTTTGAAATGTTGAAATGTTGAAATCAGGACGGTTGAAATGTTTTGAAATTTTGAAATAAATTGAAATTTGAAATTTGAAATTGTCCTACCGGTATTATATTGAAATTTGAAATCTTGAAATTTGAAATTTTGAAATATTGAAATTTGAAATTTGAAATCGTTCTTGAAATTTTTGAAATTACATTGAAATTTGAAATACTCCTTGAAATGATTGAAATCTTGAAATATTTGAAATTAGGTTGAAATAAGTTGAAATCTTGAAATTTGAAATCCTCTTGAAATTTGAAATCTTGAAATGCAAAACTTGAAATAGCTTTGAAATCGTTTGAAATCGCAGATTGAAATGTTGAAATTTTGAAATTTTTGAAATATTGAAATTTGAAATGGTTGAAATTTTTGAAATCAAATTGAAATTTGAAATCTTGAAATTTGAAATGCTTTTGAAATGTTGAAATGAGACTTGAAATTTTGAAATGGTTGAAATTTGAAATTGTTCTTTGAAATTTGAAATTTGAAATGCTTGAAATTCTTTGAAATGTTGAAATGCGAAGTTGAAATGCTTGAAATACGTTGAAATATTTTGAAATTTGAAATAACCGGTTGCTCCCCATTGAAATGATTGAAATAGCTCACCTTTTGAAATTTTGAAATATTGAAATTCGTTGAAATCTTGAAATTTGAAATTTGAAATGGACCCATGAGCTTGAAATTTGAAATGCTTGCCGAATGTTGAAATCTTGAAATCTCTTGAAATCCCGCCTCGTTGAAATCTTGAAATCTTGAAATATTGAAATTTCGGGCTAGACTTGAAAT"
    input_s = input("Is your input a string or File?")
    if input_s.lower() == "string":
        input_seq = input("Please enter/ paste the string:\n")
    else:
        input_seq = open(input_s, 'r')
    # motif = "TTGAAATTT"
    motif = input("Please enter the motif:\n")
    results = find_motif(input_seq, motif)
    print("Positions: ", results)


def find_motif(input_seq, motif):
    motif_locations = []
    for i in range(len(input_seq)):
        if input_seq[i:i + len(motif)] == motif:
            motif_locations.append(i + 1)
    return " ".join(map(str, motif_locations))


if __name__ == "__main__":
    main()
